import {deliverySchedule} from '../config/deliveryEvents';
import {beforeAll,describe,it,expect} from 'vitest';
import {threeDaySchedule,resolveScheduleRecipe,type CozySchedule} from '../config/cozySchedule';
import {CozyRuntime,type CozyScheduleDependencies} from './CozyRuntime';
import {customerPizzaRequests} from '../config/customerPizzaRequests';
import {recipeIngredients} from '../domain/CozyStock';
import {fundedShopCheckpoint} from './shopTestFixture';
import {validateCozyCheckpoint} from '../domain/CozyCheckpoint';
import {FINISHING_SAUCES} from '../config/ingredientCatalog';
const requests=[{recipe:'cheese' as const,price:50,finishingSauces:['sauce-white' as const]},{recipe:'mushroom' as const,price:65,finishingSauces:['sauce-pesto' as const,'sauce-hot' as const]}];
const deps:CozyScheduleDependencies={schedule:day=>({day,duration:240,grace:120,slots:[{id:'mixed',at:0,kind:'hurry',opportunity:'commercial',commercialOrdinal:4,takeaway:true}]}),resolveItems:()=>requests};
function shop(){const r=CozyRuntime.restoreCheckpoint(fundedShopCheckpoint(22000),false,deps)!;r.configureMenu('mushroom',100,true);for(const id of ['dough','sauce','cheese','mushroom',...FINISHING_SAUCES] as const)r.buy(id,3);r.openShop();return r;}
function cook(r:CozyRuntime,sauces=true){for(const ingredient of recipeIngredients(r.selectedRecipe))expect(r.dispatch({type:'ingredient',ingredient})).toBe(true);expect(r.dispatch({type:'bake'})).toBe(true);r.advanceElapsed(6000);expect(r.dispatch({type:'extract'})).toBe(true);if(sauces)for(const ingredient of r.selectedTicket!.requestedSauces)expect(r.dispatch({type:'ingredient',ingredient})).toBe(true);expect(r.dispatch({type:'box'})).toBe(true);}
describe('mixed pizza customer orders',()=>{
 beforeAll(()=>{fundedShopCheckpoint(22000);},20000);
 it('boxes next distinct recipe automatically and settles one whole receipt with exact sales and stock',()=>{const r=shop(),cash=r.state.cash,id=r.selectedTicketId;expect(r.selectedTicket?.items).toEqual(requests);cook(r);expect(r.selectedRecipe).toBe('mushroom');expect(r.state.finishingSauces).toEqual([]);expect(r.selectedTicket?.packed).toBe(1);expect(r.state.cash).toBe(cash);expect(r.dispatch({type:'deliver'})).toBe(false);cook(r);expect(r.selectedTicket?.packed).toBe(2);expect(r.dispatch({type:'deliver',commandId:'final'})).toBe(true);expect(r.dispatch({type:'deliver',sourceId:id,targetId:id,commandId:'final'})).toBe(false);expect(r.state.cash).toBe(cash+115);expect(r.lastResult?.stars).toBe(5);r.closeDay();expect(r.daySummary).toMatchObject({delivered:1,pizzasSold:2,revenue:115,cost:43});expect(r.daySummary?.salesByRecipe).toEqual([{recipe:'cheese',quantity:1,revenue:50},{recipe:'mushroom',quantity:1,revenue:65}]);expect(validateCozyCheckpoint(r.exportCheckpoint())).not.toBeNull();});
 it('missing requested finishing sauce asks once at pack and confirmed wrong item advances safely',()=>{const r=shop();cook(r,false);expect(r.deliveryPending?.reasons).toContain('Sai công thức');expect(r.selectedTicket?.packed).toBe(0);expect(r.confirmDelivery()).toBe(true);expect(r.selectedRecipe).toBe('mushroom');expect(r.selectedTicket?.packed).toBe(1);cook(r);expect(r.dispatch({type:'deliver'})).toBe(true);expect(r.deliveryPending?.reasons).toContain('Sai công thức');expect(r.confirmDelivery()).toBe(true);expect(r.lastResult?.stars).toBe(3);});
 it('staff adds each requested finishing sauce after extraction and waits before box',()=>{const r=CozyRuntime.restoreCheckpoint(fundedShopCheckpoint(22000),false,deps)!;r.configureMenu('mushroom',100,true);for(const role of ['prep','oven','box'] as const)r.hireStaff(role,role);for(const id of ['dough','sauce','cheese','mushroom',...FINISHING_SAUCES] as const)r.buy(id,3);r.openShop();r.advanceElapsed(25000);expect(r.selectedTicket?.packed).toBe(2);for(const id of FINISHING_SAUCES)expect(r.owned(id)).toBe(2);expect(r.state.cash).toBeLessThan(22000);expect(r.dispatch({type:'deliver'})).toBe(true);expect(r.lastResult?.stars).toBe(5);});
 it('keeps deterministic request generation within the menu and counts finishing demand in forecast',()=>{const slot={id:'stable',at:0,kind:'hurry' as const,opportunity:'commercial' as const,commercialOrdinal:4,takeaway:true};const a=customerPizzaRequests(3,1,slot,['cheese','mushroom'],'cheese',()=>50);expect(a).toEqual(customerPizzaRequests(3,1,slot,['cheese','mushroom'],'cheese',()=>50));expect(new Set(a.map(i=>i.recipe)).size).toBe(a.length);expect(customerPizzaRequests(3,1,slot,['cheese'],'cheese',()=>50)).toHaveLength(1);const r=CozyRuntime.restoreCheckpoint(fundedShopCheckpoint(22000),false,deps)!;expect(r.marketForecast.rows.map(row=>row.ingredient)).toEqual(expect.arrayContaining([...FINISHING_SAUCES]));});
 it('packs mixed app items with one rider fee and one final payment',()=>{const appDeps:CozyScheduleDependencies={...deps,schedule:day=>({day,duration:240,grace:120,slots:[{id:'appmixed',at:0,source:'app',quantity:3,kind:'hurry',opportunity:'commercial',commercialOrdinal:4,takeaway:true}]})};const r=CozyRuntime.restoreCheckpoint(fundedShopCheckpoint(22000),false,appDeps)!;r.configureMenu('mushroom',100,true);r.configureDeliveryApp(true,'app');for(const id of ['dough','sauce','cheese','mushroom',...FINISHING_SAUCES] as const)r.buy(id,3);r.openShop();r.bookShipper(r.selectedTicketId,'book');const cash=r.state.cash;cook(r);expect(r.state.cash).toBe(cash);cook(r);expect(r.dispatch({type:'deliver'})).toBe(true);expect(r.state.cash).toBe(cash+110);expect(r.lastResult?.price).toBe(115);r.closeDay();expect(r.daySummary).toMatchObject({pizzasSold:2,delivered:1,deliveryFees:5,revenue:115});expect(validateCozyCheckpoint(r.exportCheckpoint())).not.toBeNull();});
 it.each(['expired','closed'] as const)('retains partially packed stock costs without sales when mixed order is %s',outcome=>{const r=shop(),cash=r.state.cash;cook(r);expect(r.selectedTicket?.packed).toBe(1);if(outcome==='expired')r.advanceElapsed(90000);expect(r.closeDay()).toBe(true);expect(r.daySummary).toMatchObject({delivered:0,pizzasSold:0,revenue:0,cost:17,abandoned:1});const report=r.daySummary!;expect(report.reviews[0]).toMatchObject({source:'shop',quantity:2,outcome});expect(report.reviews[0].soldItems).toBeUndefined();expect(report.accounts.openingInventoryValue+report.purchases-report.cost-report.expired).toBe(report.accounts.inventory.value);expect(r.state.cash).toBe(cash-20);const restored=CozyRuntime.restoreCheckpoint(r.exportCheckpoint())!;expect(restored).not.toBeNull();expect(restored.stockLots).toEqual(r.stockLots);expect(restored.state.cash).toBe(r.state.cash);});
 it('cancels a missing sauce pack then corrects and retries without repeated ingredient consumption',()=>{const r=shop(),initial=r.owned('dough');cook(r,false);expect(r.state.stage).toBe('boxed');expect(r.selectedTicket?.packed).toBe(0);expect(r.cancelDelivery()).toBe(true);expect(r.state.stage).toBe('ready');expect(r.dispatch({type:'ingredient',ingredient:'sauce-white'})).toBe(true);expect(r.dispatch({type:'ingredient',ingredient:'sauce-white'})).toBe(false);expect(r.dispatch({type:'box'})).toBe(true);expect(r.selectedTicket?.packed).toBe(1);expect(r.selectedRecipe).toBe('mushroom');expect(r.owned('dough')).toBe(initial-1);expect(r.owned('sauce-white')).toBe(2);});
 it('uses the same seeded occasional six-capacity bursts and item demand for forecast and actual day two',()=>{
  const r=new CozyRuntime(false,true,{eventSeed:13});r.claimTestCode('VIETVUIVE');expect(r.upgradeShop('queue','six')).toBe(true);r.openShop();r.closeDay();
  const forecast=r.marketForecast;expect(r.openNextDay()).toBe(true);const actual=(r as unknown as {schedule:CozySchedule}).schedule;
  expect(actual).toEqual(deliverySchedule(threeDaySchedule(2,{queueCapacity:6,customerSeed:'13',regularDay1Stars:null,regularLatestStars:null,helpSucceeded:false,helpOfferEligible:undefined,referral:false}),false));
  const demands=new Map<string,number>();for(const slot of actual.slots){const first=resolveScheduleRecipe(slot,r.menuRecipes);if(first)for(const item of customerPizzaRequests(13,2,slot,r.menuRecipes,first,()=>0)){for(const id of [...recipeIngredients(item.recipe),...item.finishingSauces])demands.set(id,(demands.get(id)??0)+1);}}
  for(const row of forecast.rows)expect(row.needed).toBe(Math.ceil((demands.get(row.ingredient)??0)*1.1));r.advanceElapsed(10000);expect(r.tickets).toHaveLength(1);
  const at=actual.slots.find((slot,index)=>index>0&&slot.at===actual.slots[index-1].at)!.at,batch=actual.slots.filter(slot=>slot.at===at);expect(batch).toHaveLength(6);
  const concurrent=new CozyRuntime(false,true,{schedule:day=>({...actual,day,slots:batch.map(slot=>({...slot,at:10}))})});concurrent.claimTestCode('VIETVUIVE');expect(concurrent.upgradeShop('queue','batch-six')).toBe(true);expect(concurrent.openShop()).toBe(true);concurrent.advanceElapsed(10000);expect(concurrent.tickets).toHaveLength(6);
 });
 it('protects fully packed counter items from discard and remake before final settlement',()=>{const r=shop();cook(r);cook(r);const stock=JSON.stringify(r.stockLots);expect(r.selectedTicket?.packed).toBe(2);expect(r.requestDiscard()).toBe(false);expect(r.remake()).toBe(false);expect(r.dispatch({type:'bake'})).toBe(false);expect(JSON.stringify(r.stockLots)).toBe(stock);expect(r.dispatch({type:'deliver'})).toBe(true);expect(r.lastResult?.price).toBe(115);});
 it('rejects altered item receipt sums on save restore',()=>{const r=shop();cook(r);cook(r);r.dispatch({type:'deliver'});r.closeDay();const saved=r.exportCheckpoint();saved.reports[saved.reports.length-1].reviews[0].soldItems![0].price++;expect(validateCozyCheckpoint(saved)).toBeNull();});
 it('settles and restores the actual day-seven campaign with over fifty completed customer reviews',()=>{
  const r=new CozyRuntime(false,true,{eventSeed:13});r.claimTestCode('VIETVUIVE');r.configureMenu('mushroom',100,false);
  expect(r.upgradeShop('queue','six-high')).toBe(true);expect(r.upgradeShop('oven','hot-one')).toBe(true);expect(r.upgradeShop('oven','hot-two')).toBe(true);
  for(let day=1;day<=6;day++){expect(day===1?r.openShop():r.openNextDay()).toBe(true);expect(r.closeDay()).toBe(true);}
  for(const ingredient of ['dough','sauce','cheese',...FINISHING_SAUCES] as const)expect(r.buy(ingredient,100)).toBe(true);
  expect(r.openNextDay()).toBe(true);
  for(let iteration=0;iteration<7000&&r.shiftClock.phase!=='awaiting-close';iteration++){
   if(r.shopPhase==='delivered')r.continueShift();
   const ticket=r.selectedTicket;
   if(ticket){for(const ingredient of recipeIngredients(r.selectedRecipe))r.dispatch({type:'ingredient',ingredient});expect(r.dispatch({type:'bake'})).toBe(true);r.advanceElapsed(2000);expect(r.dispatch({type:'extract'})).toBe(true);for(const ingredient of r.selectedTicket!.requestedSauces)r.dispatch({type:'ingredient',ingredient});r.dispatch({type:'box'});expect(r.dispatch({type:'deliver'})).toBe(true);if(r.bargainPending)r.resolveBargain(true);}
   else r.advanceElapsed(50);
  }
  expect(r.closeDay()).toBe(true);expect(r.daySummary!.reviews.length).toBeGreaterThan(50);expect(r.daySummary!.delivered).toBeGreaterThan(50);const restored=CozyRuntime.restoreCheckpoint(r.exportCheckpoint())!;expect(restored).not.toBeNull();expect(restored.state.cash).toBe(r.state.cash);expect(restored.stockLots).toEqual(r.stockLots);
 },20000);
});
