import {expect,test,type Page} from '@playwright/test';
import {build} from 'esbuild';
type Control={id:string;x:number;y:number;width:number;height:number;enabled:boolean};
async function data(page:Page,key:string){return JSON.parse(await page.locator('canvas').getAttribute('data-'+key)??'null');}
async function tap(page:Page,id:string){let c:Control|undefined;await expect.poll(async()=>{c=((await data(page,'controls'))??[]).find((v:Control)=>v.id===id&&v.enabled);return !!c;}).toBe(true);const b=(await page.locator('canvas').boundingBox())!,r=c!;expect(r.width*b.width/360).toBeGreaterThanOrEqual(48);expect(r.height*b.height/640).toBeGreaterThanOrEqual(48);await page.touchscreen.tap(b.x+(r.x+r.width/2)*b.width/360,b.y+(r.y+r.height/2)*b.height/640);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}
async function ready(page:Page){await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('ready');}
async function active(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{const q=indexedDB.open('pizza-cozy-checkpoints',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,tx=db.transaction('latest','readonly'),r=tx.objectStore('latest').get('active');tx.oncomplete=()=>{db.close();resolve(r.result);};};}));}
async function seed(page:Page){
 const moduleName:string='node:path';const paths:{resolve:(p:string)=>string}=await import(moduleName);
 const bundle=await build({stdin:{resolveDir:paths.resolve('.'),loader:'ts',contents:`import Phaser from 'phaser';import {CozyScene} from './src/scenes/CozyScene';import {CozyCampaignSession} from './src/runtime/CozyCampaignSession';import {CozySaveRepository} from './src/infrastructure/CozySaveRepository';import {fundedShopCheckpoint} from './src/runtime/shopTestFixture';(async()=>{const repo=new CozySaveRepository(),loaded=await repo.load();const result=await repo.commit({campaignId:'epic7',commitId:'earned',sourceRevision:0,replacementToken:loaded.replacementToken,payload:fundedShopCheckpoint()});if(!result.ok)throw Error(result.message);const session=new CozyCampaignSession(repo),r=await session.load();(window as any).epic7={session,r};new Phaser.Game({type:Phaser.AUTO,parent:'fixture',width:360,height:640,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[new CozyScene(r,undefined,undefined,undefined,session.lifecycle,session)]});})();`},bundle:true,platform:'browser',format:'iife',minify:true,define:{'import.meta.env.BASE_URL':'"/"'},write:false});
 await page.route('**/assets/index-*.js',route=>route.abort());await page.goto('/');await page.setContent('<style>html,body{margin:0;height:100%;overflow:hidden}#fixture{height:100%;width:100%}</style><div id="fixture"></div>');await page.addScriptTag({content:bundle.outputFiles[0].text});await ready(page);
}
test('insufficient funds never purchase or change the six-card layout',async({page},info)=>{
 await page.goto('/?mode=shop');await ready(page);const before=await active(page);await tap(page,'summary-tab-shop');await tap(page,'shop-section-decoration');expect((await data(page,'controls')).filter((c:Control)=>c.id.startsWith('shop-item-'))).toHaveLength(6);await page.locator('canvas').screenshot({path:info.outputPath('decoration.png')});await tap(page,'shop-item-table-plant');expect((await data(page,'labels')).some((l:{text:string})=>l.text.includes('Còn thiếu 200 xu'))).toBe(true);expect((await data(page,'controls')).find((c:Control)=>c.id==='shop-item-confirm').enabled).toBe(false);await tap(page,'shop-item-cancel');expect(await active(page)).toEqual(before);
 await tap(page,'shop-back');await tap(page,'shop-section-amenities');await page.locator('canvas').screenshot({path:info.outputPath('amenities.png')});await tap(page,'shop-item-customer-tables');expect((await data(page,'labels')).some((l:{text:string})=>l.text.includes('+10% thời gian chờ'))).toBe(true);expect((await data(page,'labels')).some((l:{text:string})=>l.text.includes('Còn thiếu 3.700 xu'))).toBe(true);expect((await data(page,'controls')).find((c:Control)=>c.id==='shop-item-confirm').enabled).toBe(false);await tap(page,'notification-close');expect(await active(page)).toEqual(before);
});
test('tables buy and placement persist as patience only; capacity stays four until expansion and six thereafter',async({page},info)=>{
 await seed(page);const cash=(await active(page)).payload.stock.cash;expect(await data(page,'queue-capacity')).toBe(4);
 await tap(page,'summary-tab-shop');await tap(page,'shop-section-amenities');await tap(page,'shop-item-customer-tables');await page.locator('canvas').screenshot({path:info.outputPath('tables-patience.png')});await tap(page,'shop-item-confirm');await ready(page);
 expect((await data(page,'shop-items')).effects.patience).toBe(0);expect(await data(page,'queue-capacity')).toBe(4);
 await tap(page,'shop-item-customer-tables');await tap(page,'shop-item-confirm');await tap(page,'shop-item-confirm');await ready(page);
 expect((await data(page,'shop-items')).effects.patience).toBe(.10);expect(await data(page,'queue-capacity')).toBe(4);expect((await active(page)).payload.stock.cash).toBe(cash-4000);
 await page.unroute('**/assets/index-*.js');await page.goto('/?mode=shop');await ready(page);
 expect((await data(page,'shop-items')).effects.patience).toBe(.10);expect(await data(page,'queue-capacity')).toBe(4);
 const frames=(await data(page,'kitchen-layout')).customerFrames;expect(frames).toHaveLength(6);expect(frames.map((f:{x:number})=>f.x)).toEqual([17,72,127,182,237,292]);
 await tap(page,'summary-tab-shop');await tap(page,'shop-section-expansion');expect((await data(page,'controls')).filter((c:Control)=>c.id.includes('upgrade-queue'))).toHaveLength(1);
 expect((await data(page,'controls')).some((c:Control)=>c.id.includes('expansion-2'))).toBe(false);await page.locator('canvas').screenshot({path:info.outputPath('expansion-no-second-effect.png')});
 await tap(page,'summary-upgrade-queue');await tap(page,'hub-upgrade-confirm');await ready(page);expect(await data(page,'queue-capacity')).toBe(6);
 expect((await data(page,'controls')).find((c:Control)=>c.id==='summary-upgrade-queue').enabled).toBe(false);expect((await data(page,'kitchen-layout')).customerFrames).toEqual(frames);
 await page.reload();await ready(page);expect(await data(page,'queue-capacity')).toBe(6);expect((await data(page,'shop-items')).effects.patience).toBe(.10);expect((await data(page,'kitchen-layout')).customerFrames).toEqual(frames);
});
test('failed purchase keeps cash and ownership; retry, placement, cancel, store and reload stay consistent',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const put=IDBObjectStore.prototype.put;let failed=sessionStorage.getItem('epic7-write-failed')==='1';IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){if(key==='active'&&value.payload?.shop?.spent===500&&!failed){failed=true;sessionStorage.setItem('epic7-write-failed','1');this.transaction.abort();throw new DOMException('Epic7 write failure','QuotaExceededError');}return key===undefined?put.call(this,value):put.call(this,value,key);};});
 await seed(page);const before=await active(page),cash=before.payload.stock.cash;await tap(page,'summary-tab-shop');await tap(page,'shop-section-decoration');await tap(page,'shop-item-table-plant');await page.locator('canvas').screenshot({path:info.outputPath('buy-item.png')});await tap(page,'shop-item-cancel');expect(await active(page)).toEqual(before);await tap(page,'shop-item-table-plant');await tap(page,'shop-item-confirm');await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('error');expect(Number(await page.locator('canvas').getAttribute('data-cash'))).toBe(cash);expect((await data(page,'shop-items')).acquired).toEqual([]);expect(await active(page)).toEqual(before);
 await tap(page,'save-retry');await ready(page);expect(Number(await page.locator('canvas').getAttribute('data-cash'))).toBe(cash-500);expect((await data(page,'shop-items')).effects.visitors).toBe(0);const bought=await active(page);
 await tap(page,'shop-item-table-plant');await tap(page,'shop-item-confirm');await page.locator('canvas').screenshot({path:info.outputPath('placement-preview.png')});await tap(page,'shop-item-cancel');expect(await active(page)).toEqual(bought);await tap(page,'shop-item-table-plant');await tap(page,'shop-item-confirm');await tap(page,'shop-item-confirm');await ready(page);expect((await data(page,'shop-items')).effects.visitors).toBe(.03);
 await tap(page,'shop-back');await page.locator('canvas').screenshot({path:info.outputPath('placed-preview.png')});await page.unroute('**/assets/index-*.js');await page.goto('/?mode=shop');await ready(page);expect((await data(page,'shop-items')).effects.visitors).toBe(.03);await tap(page,'summary-tab-shop');await tap(page,'shop-section-decoration');await tap(page,'shop-item-table-plant');await tap(page,'shop-item-confirm');await tap(page,'shop-item-confirm');await ready(page);expect((await data(page,'shop-items')).effects.visitors).toBe(0);expect((await data(page,'shop-items')).acquired).toHaveLength(1);expect(Number(await page.locator('canvas').getAttribute('data-cash'))).toBe(cash-500);await page.reload();await ready(page);expect((await data(page,'shop-items')).acquired[0].placedSlot).toBeNull();expect(errors).toEqual([]);
});
test('new oven and queue prices persist and capital is charged in one day report only',async({page},info)=>{
 await seed(page);const before=await active(page),cash=before.payload.stock.cash;await tap(page,'summary-tab-shop');await tap(page,'shop-section-equipment');
 for(const price of [2000,5000]){await tap(page,'summary-upgrade-oven');expect((await data(page,'hub-upgrade')).cost).toBe(price);await tap(page,'hub-upgrade-confirm');await ready(page);}
 await tap(page,'shop-back');await tap(page,'shop-section-expansion');await page.locator('canvas').screenshot({path:info.outputPath('expansion.png')});await tap(page,'summary-upgrade-queue');expect((await data(page,'hub-upgrade')).cost).toBe(6000);await tap(page,'hub-upgrade-confirm');await ready(page);const saved=await active(page);expect(saved.payload.stock.cash).toBe(cash-13000);expect(saved.payload.upgrades).toMatchObject({ovenLevel:2,queueLevel:1,spent:13000,pendingSpent:13000});
 await page.evaluate(()=>{const {r,session}=(window as any).epic7;r.openShop();session.closeDay();});await ready(page);const after=await active(page);expect(after.payload.reports.at(-1).accounts.capitalPurchases).toBe(13000);expect(after.payload.upgrades.pendingSpent).toBe(0);await page.unroute('**/assets/index-*.js');await page.goto('/?mode=shop');await ready(page);expect((await active(page)).payload.upgrades).toMatchObject({ovenLevel:2,queueLevel:1,spent:13000,pendingSpent:0});
});
