import {expect,test,type Page} from '@playwright/test';
import {build} from 'esbuild';
type Control={id:string;x:number;y:number;width:number;height:number;enabled:boolean};
async function data(page:Page,key:string){return JSON.parse(await page.locator('canvas').getAttribute('data-'+key)??'null');}
async function tap(page:Page,id:string){
 const canvas=page.locator('canvas');let c:Control|undefined;
 await expect.poll(async()=>{const cs=(await data(page,'controls')) as Control[];const resume=cs.find(c=>c.id==='resume'&&c.enabled);if(resume&&id!=='resume'&&(await canvas.getAttribute('data-paused')??'').includes('gap')){const b=(await canvas.boundingBox())!;await page.touchscreen.tap(b.x+(resume.x+resume.width/2)*b.width/360,b.y+(resume.y+resume.height/2)*b.height/640);return false;}c=cs.find(c=>c.id===id&&c.enabled);return !!c;}).toBe(true);
 const b=(await canvas.boundingBox())!,r=c!;expect(r.width*b.width/360).toBeGreaterThanOrEqual(48);expect(r.height*b.height/640).toBeGreaterThanOrEqual(48);await page.touchscreen.tap(b.x+(r.x+r.width/2)*b.width/360,b.y+(r.y+r.height/2)*b.height/640);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
}
async function active(page:Page){return page.evaluate(async()=>new Promise<{revision:number;payload:{stock:{cash:number};ownedRecipes:string[];recipePurchases:{spent:number}}}>((resolve,reject)=>{const r=indexedDB.open('pizza-cozy-checkpoints',1);r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result,tx=db.transaction('latest','readonly'),q=tx.objectStore('latest').get('active');tx.oncomplete=()=>{db.close();resolve(q.result);};};}));}
async function ready(page:Page){await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('ready');}
test('recipe cancel, failed atomic save, retry and reload preserve one purchase',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const put=IDBObjectStore.prototype.put;let failed=false;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const e=value as {payload?:{recipePurchases?:{spent:number}}};if(key==='active'&&e.payload?.recipePurchases?.spent===150&&!failed){failed=true;this.transaction.abort();throw new DOMException('Injected recipe failure','QuotaExceededError');}return key===undefined?put.call(this,value):put.call(this,value,key);};});
 await page.goto('/?mode=shop');await ready(page);const canvas=page.locator('canvas'),before=await active(page);
 await tap(page,'summary-tab-shop');await tap(page,'shop-section-menu');await canvas.screenshot({path:info.outputPath('recipe-menu.png')});
 await tap(page,'shop-recipe-buy-sausage');await tap(page,'recipe-buy-cancel');await expect(canvas).toHaveAttribute('data-cash','300');expect(await active(page)).toEqual(before);
 await tap(page,'shop-recipe-buy-sausage');await canvas.screenshot({path:info.outputPath('recipe-confirmation.png')});await tap(page,'recipe-buy-confirm');
 await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('error');expect(await active(page)).toEqual(before);await expect(canvas).toHaveAttribute('data-cash','150');expect((await data(page,'controls')).some((c:Control)=>c.id==='summary-open-first-day'&&c.enabled)).toBe(false);
 await tap(page,'save-retry');await ready(page);const saved=await active(page);expect(saved).toMatchObject({revision:2,payload:{stock:{cash:150},ownedRecipes:['cheese','mushroom','sausage'],recipePurchases:{spent:150}}});
 await page.reload();await ready(page);await expect(canvas).toHaveAttribute('data-cash','150');await tap(page,'summary-tab-shop');await tap(page,'shop-section-menu');expect((await data(page,'controls')).some((c:Control)=>c.id==='shop-price-sausage'&&c.enabled)).toBe(true);expect((await data(page,'controls')).some((c:Control)=>c.id==='shop-recipe-buy-sausage')).toBe(false);
 await tap(page,'shop-menu-next');await canvas.screenshot({path:info.outputPath('recipe-menu-locked.png')});expect((await data(page,'controls')).filter((c:Control)=>c.id.startsWith('shop-recipe-buy-')&&c.enabled)).toEqual([]);await tap(page,'shop-menu-next');await canvas.screenshot({path:info.outputPath('recipe-menu-last.png')});expect(errors).toEqual([]);
});
test('all eight menu recipes and direct targets produce a paged read-only full forecast',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const specifier:string='node:path';const paths:{resolve:(p:string)=>string}=await import(specifier);
 const bundle=await build({stdin:{resolveDir:paths.resolve('.'),loader:'ts',contents:`import Phaser from 'phaser';import {CozyScene} from './src/scenes/CozyScene';import {CozyRuntime} from './src/runtime/CozyRuntime';import {RECIPE_CATALOG} from './src/config/recipeCatalog';const r=new CozyRuntime(false,true);r['stock'].receive(2000);for(const recipe of RECIPE_CATALOG)if(recipe.purchasePrice)r.buyRecipe(recipe.id,'fixture:'+recipe.id);new Phaser.Game({type:Phaser.AUTO,parent:'fixture',width:360,height:640,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[new CozyScene(r)]});`},bundle:true,platform:'browser',format:'iife',minify:true,define:{'import.meta.env.BASE_URL':'"/"'},write:false});
 await page.route('**/assets/index-*.js',route=>route.abort());await page.goto('/');await page.setContent('<style>html,body{margin:0;height:100%;overflow:hidden}#fixture{height:100%;width:100%}</style><div id="fixture"></div>');await page.addScriptTag({content:bundle.outputFiles[0].text});const canvas=page.locator('canvas');await expect(canvas).toHaveAttribute('data-screen','preparation-hub');
 await tap(page,'summary-tab-shop');await tap(page,'shop-section-menu');await tap(page,'shop-menu-next');await canvas.screenshot({path:info.outputPath('recipe-menu-owned.png')});await tap(page,'shop-menu-next');expect((await data(page,'controls')).some((c:Control)=>c.id==='shop-price-ham-pineapple'&&c.enabled)).toBe(true);
 await tap(page,'summary-tab-stock');await tap(page,'stock-suggestions');const cash=await canvas.getAttribute('data-cash'),stock=await data(page,'stock');
 for(const [i,ids] of [['cheese','mushroom','sausage'],['pepperoni','vegetable','chicken-bbq'],['seafood','ham-pineapple']].entries()){
  if(i)await tap(page,'stock-plan-menu-next');
  for(const id of ids){await tap(page,'stock-plan-quantity-'+id);await page.getByRole('textbox').fill('2');await tap(page,'stock-plan-input-apply');}
 }
 const forecast=await data(page,'stock-forecast');expect(forecast.find((r:{id:string})=>r.id==='dough')).toMatchObject({need:16,available:0,missing:16});expect(forecast.find((r:{id:string})=>r.id==='sauce')).toMatchObject({need:14});expect(forecast.find((r:{id:string})=>r.id==='sauce-bbq')).toMatchObject({need:2});expect(forecast).toHaveLength(16);
 await canvas.screenshot({path:info.outputPath('full-menu-plan.png')});for(let i=0;i<3;i++)await tap(page,'stock-plan-ingredients-next');await canvas.screenshot({path:info.outputPath('full-menu-plan-last.png')});await tap(page,'stock-plan-close');await expect(canvas).toHaveAttribute('data-cash',cash!);expect(await data(page,'stock')).toEqual(stock);expect(errors).toEqual([]);
});
test('supplier discounted row and immediate purchase use the same next-day price',async({page},info)=>{
 const specifier:string='node:path';const paths:{resolve:(p:string)=>string}=await import(specifier);
 const bundle=await build({stdin:{resolveDir:paths.resolve('.'),loader:'ts',contents:`import Phaser from 'phaser';import {CozyScene} from './src/scenes/CozyScene';import {CozyRuntime} from './src/runtime/CozyRuntime';const r=new CozyRuntime(false,true);r['stock'].receive(2000);r.buy('dough',100);r.openShop();r.closeDay();r['stock'].debit(r.state.cash-7);new Phaser.Game({type:Phaser.AUTO,parent:'fixture',width:360,height:640,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[new CozyScene(r)]});`},bundle:true,platform:'browser',format:'iife',minify:true,define:{'import.meta.env.BASE_URL':'"/"'},write:false});
 await page.route('**/assets/index-*.js',route=>route.abort());await page.goto('/');await page.setContent('<style>html,body{margin:0;height:100%;overflow:hidden}#fixture{width:100%;height:100%}</style><div id="fixture"></div>');await page.addScriptTag({content:bundle.outputFiles[0].text});const canvas=page.locator('canvas');await expect(canvas).toHaveAttribute('data-screen','day-summary');
 await tap(page,'summary-tab-market');await tap(page,'market-filter-base');expect((await data(page,'market-rows')).find((r:{id:string})=>r.id==='cheese').unitPrice).toBe(7);await tap(page,'market-buy-cheese');
 expect(await data(page,'market-purchase')).toBeNull();await canvas.screenshot({path:info.outputPath('supplier-purchase.png')});await expect(canvas).toHaveAttribute('data-cash','0');expect((await data(page,'stock')).find((r:{id:string})=>r.id==='cheese').owned).toBe(1);
});
