import {expect,test,type Page} from '@playwright/test';
import {build} from 'esbuild';
type Control={id:string;x:number;y:number;width:number;height:number;enabled:boolean};
async function data(page:Page,key:string){return JSON.parse(await page.locator('canvas').getAttribute('data-'+key)??'null');}
async function tap(page:Page,id:string){let c:Control|undefined;await expect.poll(async()=>{c=((await data(page,'controls'))??[]).find((v:Control)=>v.id===id&&v.enabled);return !!c;}).toBe(true);const b=(await page.locator('canvas').boundingBox())!,r=c!;expect(r.width*b.width/360).toBeGreaterThanOrEqual(48);expect(r.height*b.height/640).toBeGreaterThanOrEqual(48);await page.touchscreen.tap(b.x+(r.x+r.width/2)*b.width/360,b.y+(r.y+r.height/2)*b.height/640);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}
async function ready(page:Page){await expect.poll(async()=>!!(await data(page,'staff-state'))&&(await data(page,'save-state'))?.state==='ready').toBe(true);}
async function active(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{const q=indexedDB.open('pizza-cozy-checkpoints',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,tx=db.transaction('latest','readonly'),r=tx.objectStore('latest').get('active');tx.oncomplete=()=>{db.close();resolve(r.result);};};}));}
async function seed(page:Page){
 const moduleName:string='node:path';const paths:{resolve:(p:string)=>string}=await import(moduleName);
 const bundle=await build({stdin:{resolveDir:paths.resolve('.'),loader:'ts',contents:`import Phaser from 'phaser';import {CozyScene} from './src/scenes/CozyScene';import {CozyCampaignSession} from './src/runtime/CozyCampaignSession';import {CozySaveRepository} from './src/infrastructure/CozySaveRepository';import {fundedShopCheckpoint} from './src/runtime/shopTestFixture';(async()=>{const repo=new CozySaveRepository(),loaded=await repo.load();const result=await repo.commit({campaignId:'epic8',commitId:'earned',sourceRevision:0,replacementToken:loaded.replacementToken,payload:fundedShopCheckpoint()});if(!result.ok)throw Error(result.message);const session=new CozyCampaignSession(repo),r=await session.load();(window as any).epic8={session,r};new Phaser.Game({type:Phaser.AUTO,parent:'fixture',width:360,height:640,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[new CozyScene(r,undefined,undefined,undefined,session.lifecycle,session)]});})();`},bundle:true,platform:'browser',format:'iife',minify:true,define:{'import.meta.env.BASE_URL':'"/"'},write:false});
 await page.route('**/assets/index-*.js',route=>route.abort());await page.goto('/');await page.setContent('<style>html,body{margin:0;height:100%;overflow:hidden}#fixture{height:100%;width:100%}</style><div id="fixture"></div>');await page.addScriptTag({content:bundle.outputFiles[0].text});await ready(page);
}
async function staffPage(page:Page){await tap(page,'summary-tab-shop');await tap(page,'shop-section-staff');}
async function hireAll(page:Page){for(const role of ['prep','oven','box','delivery']){await tap(page,'shop-staff-'+role);await tap(page,'staff-hire-confirm');await ready(page);}}

test('day one is locked; failed hiring and retry never lose money or duplicate staff',async({page},info)=>{
 await page.goto('/?mode=shop');await ready(page);const initial=await active(page);await staffPage(page);const cards=(await data(page,'controls')).filter((c:Control)=>c.id.startsWith('shop-staff-'));expect(cards).toHaveLength(4);expect(cards.map((c:Control)=>[c.x,c.y,c.width,c.height])).toEqual([[8,180,168,163],[184,180,168,163],[8,355,168,163],[184,355,168,163]]);
 await tap(page,'shop-staff-prep');expect((await data(page,'staff-hire')).available).toBe(false);expect((await data(page,'controls')).find((c:Control)=>c.id==='staff-hire-confirm').enabled).toBe(false);await tap(page,'notification-close');expect(await active(page)).toEqual(initial);
 await page.addInitScript(()=>{const put=IDBObjectStore.prototype.put;let failed=sessionStorage.getItem('epic8-hire-failed')==='1';IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){if(key==='active'&&value.payload?.staff?.spent===2000&&!failed){failed=true;sessionStorage.setItem('epic8-hire-failed','1');this.transaction.abort();throw new DOMException('Epic8 hire failure','QuotaExceededError');}return key===undefined?put.call(this,value):put.call(this,value,key);};});
 await seed(page);const before=await active(page),cash=before.payload.stock.cash;await staffPage(page);await tap(page,'shop-staff-prep');await page.locator('canvas').screenshot({path:info.outputPath('hire-prep.png')});await tap(page,'staff-hire-cancel');expect(await active(page)).toEqual(before);await tap(page,'shop-staff-prep');await tap(page,'staff-hire-confirm');await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('error');expect((await data(page,'staff-state')).acquired).toEqual([]);expect(await active(page)).toEqual(before);
 await tap(page,'save-retry');await ready(page);expect((await data(page,'staff-state')).acquired).toHaveLength(1);expect((await active(page)).payload.stock.cash).toBe(cash-2000);await tap(page,'shop-staff-prep');expect((await data(page,'staff-hire')).owned).toBe(true);expect((await data(page,'controls')).find((c:Control)=>c.id==='staff-hire-confirm').enabled).toBe(false);await tap(page,'staff-hire-cancel');
 await page.unroute('**/assets/index-*.js');await page.goto('/?mode=shop');await ready(page);expect((await data(page,'staff-state')).acquired).toHaveLength(1);expect((await active(page)).payload.stock.cash).toBe(cash-2000);
});

test('four fixed roles automate the shift; daily payroll and ownership persist',async({page},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await seed(page);const cash=(await active(page)).payload.stock.cash;await staffPage(page);await hireAll(page);const staffed=await active(page);expect(staffed.payload.stock.cash).toBe(cash-8000);expect((await data(page,'staff-state')).dailyWages).toBe(800);await page.locator('canvas').screenshot({path:info.outputPath('four-fixed-roles.png')});
 const result=await page.evaluate(()=>{const {r,session}=(window as any).epic8;for(const id of ['dough','sauce','cheese'])r.buy(id,30);r.openShop();for(let i=0;i<600;i++)r.advance(50);const delivered=r.lastResult?.outcome;const closed=session.closeDay();return {delivered,closed};});expect(result).toEqual({delivered:'delivered',closed:true});await ready(page);
 const saved=await active(page),report=saved.payload.reports.at(-1);expect(report.accounts.wages).toBe(800);expect(report.payroll).toMatchObject({wagesPaid:800,openingArrears:0,endingArrears:0});expect(report.accounts.capitalPurchases).toBe(8000);expect(report.accounts.endingCash).toBe(report.cash);expect(saved.payload.staff.pendingSpent).toBe(0);
 await page.unroute('**/assets/index-*.js');await page.goto('/?mode=shop');await ready(page);expect((await data(page,'staff-state')).acquired).toHaveLength(4);expect((await data(page,'staff-state')).arrears).toBe(0);expect((await data(page,'kitchen-layout')).customerFrames).toHaveLength(6);expect(errors).toEqual([]);
});

test('insufficient wages show the exact shortage and preserve unpaid salary after reload',async({page},info)=>{
 await seed(page);await staffPage(page);await hireAll(page);
 const closed=await page.evaluate(()=>{const {r,session}=(window as any).epic8;while(r.state.cash-r.price('dough')>=600){const amount=Math.min(100,Math.floor((r.state.cash-600)/r.price('dough')));if(amount<1||!r.buy('dough',amount))break;}r.openShop();return session.closeDay();});expect(closed).toBe(true);await ready(page);
 const saved=await active(page),report=saved.payload.reports.at(-1),missing=800-report.cash;expect(report.payroll).toMatchObject({wagesPaid:0,endingArrears:800});expect(saved.payload.staff.arrears).toBe(800);await expect.poll(async()=>(await data(page,'labels')).some((l:{text:string})=>l.text.includes(`Còn thiếu ${missing} xu`))).toBe(true);await page.locator('canvas').screenshot({path:info.outputPath('wage-shortage.png')});await tap(page,'hub-detail-close');expect(await active(page)).toEqual(saved);
 await page.unroute('**/assets/index-*.js');await page.goto('/?mode=shop');await ready(page);expect((await data(page,'staff-state')).arrears).toBe(800);expect((await active(page)).payload.reports.at(-1).payroll.endingArrears).toBe(800);await staffPage(page);await page.locator('canvas').screenshot({path:info.outputPath('unpaid-staff.png')});
});
