import {expect,test,type Page} from '@playwright/test';
import {build} from 'esbuild';
type Control={id:string;x:number;y:number;width:number;height:number;enabled:boolean};
async function data(page:Page,key:string){return JSON.parse(await page.locator('canvas').getAttribute('data-'+key)??'null');}
async function tap(page:Page,id:string,menu=false){let c:Control|undefined;await expect.poll(async()=>{c=((await data(page,menu?'menu-targets':'controls'))??[]).find((v:Control&{disabled?:boolean})=>v.id===id&&(menu?!v.disabled:v.enabled));return !!c;}).toBe(true);const b=(await page.locator('canvas').boundingBox())!,r=c!;expect(r.width*b.width/360).toBeGreaterThanOrEqual(48);expect(r.height*b.height/640).toBeGreaterThanOrEqual(48);await page.touchscreen.tap(b.x+(r.x+r.width/2)*b.width/360,b.y+(r.y+r.height/2)*b.height/640);await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}
async function ready(page:Page){await expect.poll(async()=>!!(await data(page,'campaign-results'))&&(!(await data(page,'save-state'))||(await data(page,'save-state'))?.state==='ready')).toBe(true);}
async function active(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{const q=indexedDB.open('pizza-cozy-checkpoints',1);q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,tx=db.transaction('latest','readonly'),r=tx.objectStore('latest').get('active');tx.oncomplete=()=>{db.close();resolve(r.result);};};}));}
async function seed(page:Page,day=29,ram=false){
 const moduleName:string='node:path';const paths:{resolve:(p:string)=>string}=await import(moduleName);
 const sessionSetup=ram?'const session=null;let r=earned;':"const repo=new CozySaveRepository(),loaded=await repo.load();const result=await repo.commit({campaignId:'epic9',commitId:'earned',sourceRevision:0,replacementToken:loaded.replacementToken,payload:earned.exportCheckpoint()});if(!result.ok)throw Error(result.message);const session=new CozyCampaignSession(repo);let r=await session.load();";
 const bundle=await build({stdin:{resolveDir:paths.resolve('.'),loader:'ts',contents:`import Phaser from 'phaser';import {CozyScene} from './src/scenes/CozyScene';import {CozyRuntime} from './src/runtime/CozyRuntime';import {CozyCampaignSession} from './src/runtime/CozyCampaignSession';import {CozySaveRepository} from './src/infrastructure/CozySaveRepository';import {fundedShopCheckpoint} from './src/runtime/shopTestFixture';(async()=>{let earned=CozyRuntime.restoreCheckpoint(fundedShopCheckpoint())!;while(earned.preparationDay<${day}){if(!earned.openShop()||!earned.closeDay())throw Error('Failed fixture day');earned=CozyRuntime.restoreCheckpoint(earned.exportCheckpoint())!;}${sessionSetup}const game=new Phaser.Game({type:Phaser.AUTO,parent:'fixture',width:360,height:640,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[new CozyScene(r,undefined,undefined,undefined,session?.lifecycle,session??undefined,enter)]});function enter(next){if(!next)return;r=next;game.scene.stop('CozyScene');game.scene.remove('CozyScene');game.scene.add('CozyScene',new CozyScene(r,undefined,undefined,undefined,session?.lifecycle,session??undefined,enter),true);}window.epic9={session,get r(){return r;}};})();`},bundle:true,platform:'browser',format:'iife',minify:true,define:{'import.meta.env.BASE_URL':'"/"'},write:false});
 await page.route('**/assets/index-*.js',route=>route.abort());await page.goto('/');await page.setContent('<style>html,body{margin:0;height:100%;overflow:hidden}#fixture{height:100%;width:100%}</style><div id="fixture"></div>');await page.addScriptTag({content:bundle.outputFiles[0].text});await ready(page);
}
async function endDay(page:Page){await tap(page,'end-day');await tap(page,'confirm-end-day');await ready(page);}

test('day29 market preparation leads to day30 final results; reload and cancelled restart preserve totals',async({page},info)=>{
 await seed(page);expect(await data(page,'campaign-progress')).toEqual({day:29,endDay:30});expect((await data(page,'hub-header-labels'))[1]).toContain('29/30');
 await tap(page,'summary-tab-market');await tap(page,'market-buy-dough');await tap(page,'market-purchase-confirm');expect((await data(page,'campaign-progress')).day).toBe(29);await tap(page,'summary-open-first-day');await endDay(page);
 const day29=await active(page);expect(day29.payload.day).toBe(30);expect(day29.payload.terminal).toBe(false);await page.locator('canvas').screenshot({path:info.outputPath('prepare-day30.png')});await tap(page,'summary-tab-market');await tap(page,'market-buy-dough');await tap(page,'market-purchase-confirm');await tap(page,'summary-open-next-day');expect((await data(page,'campaign-progress')).day).toBe(30);await endDay(page);
 await expect.poll(async()=>(await data(page,'controls')).some((c:Control)=>c.id==='summary-final-close')).toBe(true);const final=await active(page),totals=await data(page,'campaign-results');expect(final.payload).toMatchObject({day:30,terminal:true,campaignEndDay:30});expect(totals.daysCompleted).toBe(30);expect(totals.revenue).toBe(final.payload.reports.reduce((n:number,r:any)=>n+r.revenue,0));expect(totals.cash).toBe(final.payload.stock.cash);expect((await data(page,'controls')).some((c:Control)=>c.id==='summary-open-next-day')).toBe(false);await page.locator('canvas').screenshot({path:info.outputPath('campaign-complete.png')});
 await tap(page,'summary-new-campaign');await page.locator('canvas').screenshot({path:info.outputPath('restart-confirm.png')});await tap(page,'market-new-cancel');expect(await active(page)).toEqual(final);expect(await data(page,'campaign-results')).toEqual(totals);await tap(page,'summary-final-result');await tap(page,'notification-close');expect(await active(page)).toEqual(final);
 await page.unroute('**/assets/index-*.js');await page.goto('/');await tap(page,'menu-continue',true);await ready(page);expect(await data(page,'campaign-results')).toEqual(totals);await tap(page,'summary-final-result');expect((await data(page,'labels')).some((l:{text:string})=>l.text.includes('Hoàn thành chiến dịch'))).toBe(true);await tap(page,'summary-final-close');await tap(page,'summary-tab-market');expect((await data(page,'controls')).some((c:Control)=>c.id==='market-buy-dough'&&c.enabled)).toBe(false);expect(await active(page)).toEqual(final);
});

test('failed final commit and failed restart keep the saved campaign; retries are atomic',async({page})=>{
 await page.addInitScript(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){const final=key==='active'&&value.payload?.reports?.at(-1)?.ending==='complete',fresh=key==='active'&&value.payload?.reports?.length===0;const flag=final?'epic9-final-failed':fresh?'epic9-new-failed':'';if(flag&&!sessionStorage.getItem(flag)){sessionStorage.setItem(flag,'1');this.transaction.abort();throw new DOMException('Epic9 failure','QuotaExceededError');}return key===undefined?put.call(this,value):put.call(this,value,key);};});
 await seed(page,30);const old=await active(page);await tap(page,'summary-open-first-day');await tap(page,'end-day');await tap(page,'confirm-end-day');await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('error');const totals=await data(page,'campaign-results');expect(await active(page)).toEqual(old);await tap(page,'save-retry');await ready(page);const final=await active(page);expect(final.payload.terminal).toBe(true);expect(await data(page,'campaign-results')).toEqual(totals);
 await tap(page,'summary-new-campaign');await tap(page,'market-new-confirm');await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('error');expect(await active(page)).toEqual(final);expect(await data(page,'campaign-results')).toEqual(totals);await tap(page,'save-retry');await ready(page);const fresh=await active(page);expect(fresh.campaignId).not.toBe(final.campaignId);expect(fresh.payload).toMatchObject({day:1,terminal:false,campaignEndDay:30,stock:{cash:300},reports:[]});expect((await data(page,'campaign-results')).daysCompleted).toBe(0);expect((await data(page,'campaign-progress')).day).toBe(1);
});

test('a completed RAM campaign restarts through a fresh runtime after confirmation',async({page})=>{
 await seed(page,30,true);await tap(page,'summary-open-first-day');await endDay(page);await tap(page,'summary-new-campaign');await tap(page,'market-new-cancel');expect((await data(page,'campaign-results')).daysCompleted).toBe(30);
 await tap(page,'summary-final-result');await tap(page,'summary-new-campaign');await tap(page,'market-new-confirm');await expect.poll(async()=>(await data(page,'campaign-progress'))?.day).toBe(1);expect((await data(page,'campaign-results')).daysCompleted).toBe(0);expect(Number(await page.locator('canvas').getAttribute('data-cash'))).toBe(300);expect((await data(page,'campaign-progress')).endDay).toBe(30);
});
