import {expect,test,type Page} from '@playwright/test';
import {build} from 'esbuild';

type Rect={x:number;y:number;width:number;height:number};
type Control=Rect&{id:string;enabled?:boolean;disabled?:boolean};
async function data(page:Page,key:string){return JSON.parse(await page.locator('canvas').getAttribute(`data-${key}`)??'null');}
async function settle(page:Page){await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));}
async function tapAt(page:Page,r:Rect){const b=(await page.locator('canvas').boundingBox())!;await page.touchscreen.tap(b.x+(r.x+r.width/2)*b.width/360,b.y+(r.y+r.height/2)*b.height/640);await settle(page);}
async function tap(page:Page,id:string,menu=false){if(!menu)await expect.poll(async()=>await page.locator('canvas').getAttribute('data-tutorial-transitioning')).not.toBe('true');let control:Control|undefined;await expect.poll(async()=>{control=((await data(page,menu?'menu-targets':'controls'))??[]).find((c:Control)=>c.id===id&&(menu?!c.disabled:c.enabled));return !!control;},{message:`actionable ${id}`}).toBe(true);await tapAt(page,control!);}
async function step(page:Page,id:string){await expect(page.locator('canvas')).toHaveAttribute('data-tutorial',id);await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('ready');}
async function active(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{const request=indexedDB.open('pizza-cozy-checkpoints',1);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,tx=db.transaction('latest','readonly'),read=tx.objectStore('latest').get('active');tx.oncomplete=()=>{db.close();resolve(read.result);};};}));}
function overlaps(a:Rect,b:Rect){return a.x<b.x+b.width&&b.x<a.x+a.width&&a.y<b.y+b.height&&b.y<a.y+a.height;}
async function geometry(page:Page){const focus:Rect=await data(page,'tutorial-focus'),card:Rect=await data(page,'tutorial-card');expect(focus).toBeTruthy();expect(card).toBeTruthy();expect(overlaps(focus,card),'instruction card must not cover focus').toBe(false);for(const r of [focus,card]){expect(r.x).toBeGreaterThanOrEqual(0);expect(r.y).toBeGreaterThanOrEqual(0);expect(r.x+r.width).toBeLessThanOrEqual(360.01);expect(r.y+r.height).toBeLessThanOrEqual(640.01);}expect((await data(page,'tutorial-guide')).opacity).toBe(.3);return focus;}
async function newGame(page:Page){await page.goto('/');await expect(page.locator('canvas')).toHaveAttribute('data-screen','menu');await tap(page,'menu-start',true);await step(page,'customer');}
const management=['summary-sales','market-ingredients','stock-owned','shop-menu','shop-decoration','shop-equipment','shop-amenities','shop-expansion','shop-staff','missions-goal','ready'];

test('new game completes isolated practice and all management focuses without changing real economy',async({page},info)=>{
 test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await newGame(page);const before=(await active(page)).payload;
 for(const id of ['customer','order','sample']){await step(page,id);await geometry(page);await page.touchscreen.tap(8,630);await expect(page.locator('canvas')).toHaveAttribute('data-tutorial',id);await tap(page,'tutorial-next');}
 await step(page,'dough');const focus=await geometry(page),controls:Control[]=await data(page,'controls');const dough=controls.find(c=>c.id==='dough')!;expect(overlaps(focus,dough)).toBe(true);const wrong=controls.find(c=>c.id==='cheese');if(wrong)await tapAt(page,wrong);await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','dough');await expect(page.locator('canvas')).toHaveAttribute('data-ingredients','');
 await page.locator('canvas').screenshot({path:info.outputPath('practice-dough.png')});
 for(const [id,action] of [['dough','dough'],['sauce','sauce'],['cheese','cheese'],['bake','bake']] as const){await step(page,id);await geometry(page);await tap(page,action);}
 await step(page,'warming');await geometry(page);await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','extract',{timeout:16000});await step(page,'extract');const oven=await page.locator('canvas').getAttribute('data-oven');await page.waitForTimeout(1000);await expect(page.locator('canvas')).toHaveAttribute('data-oven',oven!);await expect(page.locator('canvas')).toHaveAttribute('data-heat','perfect');
 for(const [id,action] of [['extract','extract'],['box','box'],['deliver','deliver']] as const){await step(page,id);await geometry(page);await tap(page,action);}
 await step(page,'complete');await expect(page.locator('canvas')).toHaveAttribute('data-cash','300');await expect(page.locator('canvas')).toHaveAttribute('data-tutorial-transitioning','false');const cashHeader=await data(page,'cash-header');expect(await geometry(page)).toEqual(cashHeader.bounds);await page.locator('canvas').screenshot({path:info.outputPath('cash-full-focus.png')});await tap(page,'tutorial-next');
 for(const id of management){await step(page,id);await geometry(page);await expect(page.locator('canvas')).toHaveAttribute('data-paused',/tutorial-management/);if(id==='summary-sales'){const hubCash=await data(page,'cash-header');expect(hubCash.location).toBe('hub');expect(hubCash.cash).toBe(cashHeader.cash);expect(hubCash.fontSize).toBe(cashHeader.fontSize);await page.locator('canvas').screenshot({path:info.outputPath('summary-cash.png')});}if(id==='shop-menu'||id==='market-ingredients')await page.locator('canvas').screenshot({path:info.outputPath(`${id}.png`)});await tap(page,'tutorial-next');}
 await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','off');await expect(page.locator('canvas')).not.toHaveAttribute('data-paused',/tutorial/);await expect.poll(async()=>(await data(page,'save-state'))?.state).toBe('ready');await expect(page.locator('canvas')).toHaveAttribute('data-summary-tab','market');const after=(await active(page)).payload;expect(after.tutorialProgress.status).toBe('completed');expect(after.stock).toEqual(before.stock);expect(after.reports).toEqual(before.reports);expect(after.day).toBe(1);expect(after.progression).toEqual(before.progression);await expect(page.locator('canvas')).toHaveAttribute('data-cash','300');
 await tap(page,'market-buy-all');const basket=await data(page,'market-basket');await tap(page,'market-purchase-confirm');await expect(page.locator('canvas')).toHaveAttribute('data-cash',String(300-basket.total));const stock=await data(page,'stock');for(const entry of basket.entries)expect(stock.find((s:{id:string})=>s.id===entry.ingredient)?.owned).toBe(entry.quantity);await tap(page,'summary-open-first-day');await expect(page.locator('canvas')).toHaveAttribute('data-shop','making');await expect(page.locator('canvas')).toHaveAttribute('data-day-summary','null');
 await page.reload();await tap(page,'menu-continue',true);await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','off');expect(errors).toEqual([]);
});

test('saved tutorial resumes the same step with compact card and no skip control',async({page},info)=>{
 await newGame(page);for(let i=0;i<3;i++)await tap(page,'tutorial-next');await step(page,'dough');await tap(page,'dough');await step(page,'sauce');await page.reload();await tap(page,'menu-continue',true);await step(page,'sauce');await expect(page.locator('canvas')).toHaveAttribute('data-ingredients','dough');await geometry(page);await page.setViewportSize({width:320,height:568});await settle(page);await geometry(page);await page.setViewportSize({width:360,height:640});await settle(page);const card=await data(page,'tutorial-card');expect(card.width).toBe(280);expect(card.height).toBeLessThan(100);expect((await data(page,'controls')).some((c:Control)=>c.id==='tutorial-skip')).toBe(false);await page.locator('canvas').screenshot({path:info.outputPath('restored-sauce.png')});await tap(page,'sauce');await step(page,'cheese');
});
async function leaseFixture(page:Page){const moduleName:string='node:path',paths:{resolve:(s:string)=>string}=await import(moduleName);const bundle=await build({stdin:{resolveDir:paths.resolve('.'),loader:'ts',contents:`import Phaser from 'phaser';import {CozyScene} from './src/scenes/CozyScene';import {CozyRuntime} from './src/runtime/CozyRuntime';const r=new CozyRuntime(false,true);r.beginInteractiveTutorial();(window as any).tutorialTest={r};new Phaser.Game({type:Phaser.AUTO,parent:'fixture',width:360,height:640,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[new CozyScene(r)]});`},bundle:true,platform:'browser',format:'iife',minify:true,define:{'import.meta.env.BASE_URL':'"/"'},write:false});await page.route('**/assets/index-*.js',r=>r.abort());await page.goto('/');await page.setContent('<style>html,body{margin:0;height:100%;overflow:hidden}#fixture{height:100%;width:100%}</style><div id="fixture"></div>');await page.addScriptTag({content:bundle.outputFiles[0].text});await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','customer');}
test('skip while baking and during management preserves another owner pause',async({page})=>{
 await leaseFixture(page);await page.evaluate(()=>{const f=(window as any).tutorialTest;for(let i=0;i<3;i++)f.r.nextTutorial();for(const ingredient of ['dough','sauce','cheese'])f.r.dispatch({type:'ingredient',ingredient});f.r.dispatch({type:'bake'});f.lease=f.r.acquirePause('user');});await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','warming');await page.evaluate(()=>(window as any).tutorialTest.r.skipTutorial());await expect(page.locator('canvas')).toHaveAttribute('data-paused','user');await expect(page.locator('canvas')).toHaveAttribute('data-ingredients','');await page.evaluate(()=>{const f=(window as any).tutorialTest;f.lease.release();});await expect(page.locator('canvas')).toHaveAttribute('data-paused','');
 await leaseFixture(page);await page.evaluate(()=>{const f=(window as any).tutorialTest;for(let i=0;i<3;i++)f.r.nextTutorial();for(const ingredient of ['dough','sauce','cheese'])f.r.dispatch({type:'ingredient',ingredient});f.r.dispatch({type:'bake'});f.r.advanceElapsed(6000);for(const type of ['extract','box','deliver'])f.r.dispatch({type});f.r.nextTutorial();f.lease=f.r.acquirePause('user');});await expect(page.locator('canvas')).toHaveAttribute('data-tutorial','summary-sales');await page.evaluate(()=>(window as any).tutorialTest.r.skipTutorial());await expect(page.locator('canvas')).toHaveAttribute('data-paused','user');await expect(page.locator('canvas')).toHaveAttribute('data-cash','300');
});

test('focus eases between steps without save popup flicker and respects reduced motion',async({page})=>{
 await newGame(page);await expect(page.locator('canvas')).toHaveAttribute('data-tutorial-transitioning','false');const previous=await data(page,'tutorial-focus');
 await page.evaluate(()=>{const state=(window as any);state.tutorialFrames=[];state.recordTutorial=true;const sample=()=>{if(!state.recordTutorial)return;const canvas=document.querySelector('canvas')!;state.tutorialFrames.push({guide:canvas.dataset.tutorialGuide,pause:canvas.dataset.pausePanel,transition:canvas.dataset.tutorialTransitioning,focus:JSON.parse(canvas.dataset.tutorialAnimatedFocus??'null')});requestAnimationFrame(sample);};requestAnimationFrame(sample);});
 await tap(page,'tutorial-next');await step(page,'order');await expect(page.locator('canvas')).toHaveAttribute('data-tutorial-transitioning','false');const frames=await page.evaluate(()=>{const state=(window as any);state.recordTutorial=false;return state.tutorialFrames;}),target=await data(page,'tutorial-focus');expect(frames.every((frame:any)=>!!frame.guide&&!frame.pause)).toBe(true);expect(frames.some((frame:any)=>frame.transition==='true'&&frame.focus.y!==previous.y&&frame.focus.y!==target.y),JSON.stringify(frames)).toBe(true);
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await tap(page,'menu-continue',true);await step(page,'order');await expect(page.locator('canvas')).toHaveAttribute('data-tutorial-transitioning','false');await tap(page,'tutorial-next');await step(page,'sample');await expect(page.locator('canvas')).toHaveAttribute('data-tutorial-transitioning','false');expect(await data(page,'tutorial-animated-focus')).toEqual(await data(page,'tutorial-focus'));
});
